### ISSUE TITLE
can't send mail to gmail 

### ISSUE THREAD

**Issue by AmmarMohamed** [guileen/node-sendmail#37]
When i sent email to gmail like <ammarshabrawy@gmail.com>
it return 

(node:28544) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: SMTP code:550 msg:550-5.7.1 [45.247.227.73] The IP you're using to send mail is not authorized to
550-5.7.1 send email directly to our servers. Please use the SMTP relay at your
550-5.7.1 service provider instead. Learn more at
550 5.7.1  https://support.google.com/mail/?p=NotAuthorizedError f64si1223417pfg.362 - gsmtp

    at response (C:\Users\AMMAR\Desktop\مستشارك\webapi\node.js-api\node_modules\sendmail\sendmail.js:213:24)
    at onLine (C:\Users\AMMAR\Desktop\مستشارك\webapi\node.js-api\node_modules\sendmail\sendmail.js:229:11)
    at Socket.<anonymous> (C:\Users\AMMAR\Desktop\مستشارك\webapi\node.js-api\node_modules\sendmail\sendmail.js:138:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
(node:28544) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Executing (default): INSERT INTO `consultent` (`id`,`name`,`email`,`password`,`type`) VALUES ('8d53f189-72fe-43f0-be39-a9c3c41cd36f','ammar22','roobah@live.com','$2a$10$SdTvB/lFnwyOTmttas9Fh.1IJnY1Bdd35zcbOzuf1vrLMg27vM5jO','employee');
Executing (default): SELECT `userId`, `code`, `sentTo`, `sentAt` FROM `UserVerificationCo` AS `UserVerificationCo` WHERE `UserVerificationCo`.`userId` = '8d53f189-72fe-43f0-be39-a9c3c41cd36f';
Executing (default): INSERT INTO `UserVerificationCo` (`userId`,`code`,`sentTo`,`sentAt`) VALUES ('8d53f189-72fe-43f0-be39-a9c3c41cd36f','2454','roobah@live.com',1495816657);
(node:28544) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: SMTP code:550 msg:550 DY-001 (BAY004-MC5F36) Unfortunately, messages from 45.247.227.73 weren't sent. Please contact your Internet service provider. You can tell them that Hotmail does not relay dynamically-assigned IP ranges. You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors.

    at response (C:\Users\AMMAR\Desktop\مستشارك\webapi\node.js-api\node_modules\sendmail\sendmail.js:213:24)
    at onLine (C:\Users\AMMAR\Desktop\مستشارك\webapi\node.js-api\node_modules\sendmail\sendmail.js:229:11)
    at Socket.<anonymous> (C:\Users\AMMAR\Desktop\مستشارك\webapi\node.js-api\node_modules\sendmail\sendmail.js:138:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)

**Comment by rcchan** [comment]
This is gmail blocking your computer's IP address.  Looks node-sendmail is working fine.
You may be able to work around some of the blocks if you have your own domain.
