### ISSUE TITLE
530 SMTP authentication is required

### ISSUE THREAD

**Issue by BananaAcid** [guileen/node-sendmail#73]
This seems to happen for all hosts using [hMailserver](https://www.hmailserver.com/) - there are a lot of them out there. You can test it against my test server using `no-reply AT myvoyagemap.com`

setup:
 Server 1: e-mail server, having dkim setup and providing "no-reply@"
 Server 2: node script sending the e-mail from "no-reply@" and dkim selector and pem are configured.

```
Error: SMTP code:530 msg:530 SMTP authentication is required.
  
      at response (C:\htdocs\com\blog\app-ui\node_modules\sendmail\sendmail.js:217:24)
      at onLine (C:\htdocs\com\blog\app-ui\node_modules\sendmail\sendmail.js:234:11)
      at Socket.<anonymous> (C:\htdocs\com\blog\app-ui\node_modules\sendmail\sendmail.js:141:11)
      at Socket.emit (events.js:210:5)
      at Socket.EventEmitter.emit (domain.js:478:20)
      at addChunk (_stream_readable.js:326:12)
      at readableAddChunk (_stream_readable.js:297:13)
      at Socket.Readable.push (_stream_readable.js:235:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:182:23),
```

**Comment by zavr-1** [comment]
it can't be the problem with the client but with the server https://www.hmailserver.com/forum/viewtopic.php?t=12373

**Comment by BananaAcid** [comment]
I am not sure what you referring to - reading that link, it seems, that a hmailserver must disable all authentication to not get hit by sendmail falsely sending an auth on connect to deliver the mails. So it seems to be an error on sendmails side. The Hosters told me, they would usually not have problems receiving mails. Same for my hmailserver.

Seems this client does not follow the specs for connecting?

Would be great, if you would have an idea, how to configure sendmail to make it work.
